export const actions = [
  {
    number: '01',
    title: '감시와 기록',
    description: '현장을 찾아가고 보고 듣고 기록합니다.',
    tag: 'WATCH',
  },
  {
    number: '02',
    title: '검증과 공유',
    description: '기록과 보도, SNS를 교차 검증하고 퍼나릅니다.',
    tag: 'VERIFY',
  },
  {
    number: '03',
    title: '행동과 참여',
    description: '집회, 캠페인, 공론장을 통해 질서 있는 참여의 장을 만듭니다.',
    tag: 'ACT',
  },
  {
    number: '04',
    title: '확산과 연대',
    description: '경계를 넘어 건강한 자유민주시민으로 거듭납니다.',
    tag: 'CONNECT',
  },
];

export const timeline = [
  {
    date: '2026. 06. 13',
    session: '1회차',
    time: '10:00 — 18:00',
    place: '수원 올림픽공원',
    title: '수원에서 시작된 첫 시민행동',
    body: '가족과 청년, 어르신이 함께한 첫 광장입니다. 오전 현장 약 40명, 하루 누적 약 300명으로 언론에 보도됐습니다.',
    link: 'https://www.joongang.co.kr/article/25436607',
    source: '중앙일보 현장 보도',
    posters: [
      { src: '/images/posters/suwon-action-01-main.jpeg', width: 360, height: 540, alt: '올림픽공원 1회차 집회 포스터', label: '첫 집회 포스터' },
    ],
    photos: [
      { src: '/images/history/session-01/field-01.webp', width: 1600, height: 1200, alt: '수원 올림픽공원에 모인 1회차 시민행동 참가자들', label: '올림픽공원 전경' },
      { src: '/images/history/session-01/field-02.webp', width: 1600, height: 1200, alt: '태극기를 든 시민들이 함께한 수원 올림픽공원 집회 현장', label: '시민 참여 현장' },
      { src: '/images/history/session-01/field-03.webp', width: 1600, height: 1200, alt: '수원 올림픽공원 산책로를 따라 선 1회차 참가자들', label: '첫 행동의 광장' },
    ],
  },
  {
    date: '2026. 06. 20',
    session: '2회차',
    time: '16:00 — 18:00',
    place: '인계동 나혜석거리',
    title: '각자의 목소리를 내는 자리',
    body: '경기 남부 시민들이 더 가까운 곳에서 참여할 수 있도록 나혜석거리로 자리를 옮겼습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DZsEGjSEmTM',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-02-main.jpeg', width: 1024, height: 1536, alt: '아이들의 미래를 지킬 공정선거 시민행동 2회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-02-mothers.jpeg', width: 360, height: 540, alt: '수원 엄마들의 재선거 촉구 2회차 포스터', label: '엄마들' },
      { src: '/images/posters/suwon-action-02-youth.jpeg', width: 360, height: 540, alt: '수원 청년들의 공정선거 시민행동 2회차 포스터', label: '청년들' },
      { src: '/images/posters/suwon-action-02-green.jpeg', width: 360, height: 540, alt: '참정권 수호 공정선거 시민행동 2회차 초록 포스터', label: '참정권 수호' },
      { src: '/images/posters/suwon-action-02-red.jpeg', width: 360, height: 540, alt: '공정선거 시민행동 2회차 붉은 포스터', label: '공정선거' },
      { src: '/images/posters/suwon-action-02-pink.jpeg', width: 360, height: 540, alt: '수원 엄마들이 일어납니다 2회차 포스터', label: '수원 엄마들' },
    ],
    photos: [
      { src: '/images/history/session-02/field-01.webp', width: 1600, height: 746, alt: '비가 내리는 나혜석거리에서 현수막을 든 2회차 참가자들', label: '우중 시민행동' },
      { src: '/images/history/session-02/field-02.webp', width: 1600, height: 746, alt: '천막 아래에서 이어진 수원 공정선거 시민행동 2회차', label: '천막 현장' },
      { src: '/images/history/session-02/field-03.webp', width: 1600, height: 746, alt: '우비와 태극기를 준비한 나혜석거리 참가자들', label: '비를 맞은 광장' },
      { src: '/images/history/session-02/field-04.webp', width: 1600, height: 901, alt: '비 오는 나혜석거리 천막 앞에 모인 시민들', label: '2회차 단체 기록' },
    ],
  },
  {
    date: '2026. 06. 27',
    session: '3회차',
    time: '16:00 — 18:00',
    place: '인계동 나혜석거리',
    title: '매주 이어지는 지역의 목소리',
    body: '두 번째 행동에 이어 같은 장소에서 시민의 질문과 목소리를 모았습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DZ2gl9CEng8',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-03-main.jpeg', width: 360, height: 540, alt: '엄마 아빠도 그때 함께 했어 공정선거 시민행동 3회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-03-invitation.jpeg', width: 360, height: 510, alt: '공정선거 시민행동 3회차 흑백 초대장 포스터', label: '초대장' },
    ],
    photos: [
      { src: '/images/history/session-03/field-01.webp', width: 1600, height: 746, alt: '나혜석거리 천막 앞에서 발언하는 3회차 참가자', label: '시민 발언' },
      { src: '/images/history/session-03/field-02.webp', width: 1600, height: 746, alt: '태극기가 걸린 수원 공정선거 시민행동 부스', label: '시민행동 부스' },
      { src: '/images/history/session-03/field-03.webp', width: 1600, height: 746, alt: '나혜석거리 천막 아래 모여 이야기를 나누는 시민들', label: '함께한 시민들' },
      { src: '/images/history/session-03/field-04.webp', width: 1600, height: 1200, alt: '아이와 가족도 함께한 공정선거 시민행동 3회차 현장', label: '가족이 함께한 광장' },
    ],
  },
  {
    date: '2026. 07. 04',
    session: '4회차',
    time: '17:00 — 19:00',
    place: '인계동 나혜석거리',
    title: '여름 저녁으로 시간을 옮기다',
    body: '여름 날씨에 맞춰 시간을 오후 5시로 변경하고 공개 채팅으로 참여 안내를 이어갔습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DaK0YJbEmHt',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-04-main.jpeg', width: 360, height: 510, alt: '6월 3일 이후 시간이 멈췄습니다 공정선거 시민행동 4회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-04-sunset.jpeg', width: 360, height: 510, alt: '자유민주주의 시간이 멈췄습니다 공정선거 시민행동 4회차 포스터', label: '태극기 시안' },
    ],
    photos: [
      { src: '/images/history/session-04/field-01.webp', width: 1600, height: 746, alt: '공정선거 시민행동 4회차 현장에 준비된 물품 상자', label: '현장 준비' },
      { src: '/images/history/session-04/field-02.webp', width: 1600, height: 746, alt: '여름 집회를 위해 준비한 음료와 간식', label: '시민을 위한 음료' },
      { src: '/images/history/session-04/field-03.webp', width: 1600, height: 746, alt: '나혜석거리 천막 앞에 모인 4회차 참가자들', label: '4회차 광장' },
      { src: '/images/history/session-04/field-04.webp', width: 1600, height: 746, alt: '태극기와 현수막이 놓인 공정선거 시민행동 4회차 현장', label: '거리의 기록' },
    ],
  },
  {
    date: '2026. 07. 11',
    session: '5회차',
    time: '17:00 — 19:00',
    place: '나혜석거리 인근',
    title: '비가 와도 이어진 다섯 번째 행동',
    body: '우천 안내와 준비 인원 모집을 공개하고 지역 상점 이용을 함께 요청했습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/Dac_eoAEvX-',
    source: '전시언 Threads 공지',
    posters: [
      { src: '/images/posters/suwon-action-05-main.jpeg', width: 360, height: 540, alt: '무엇이든 말하고 싶습니다 공정선거 시민행동 5회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-05-crowd.jpeg', width: 360, height: 540, alt: '공정선거 재선거 당일투표 수개표 시민행동 5회차 포스터', label: '현장 시안' },
    ],
    photos: [
      { src: '/images/history/session-05/field-01.webp', width: 1553, height: 1600, alt: '각자의 메시지와 태극기를 들고 선 공정선거 시민행동 5회차 참가자들', label: '각자의 목소리' },
    ],
  },
  {
    date: '2026. 07. 18',
    session: '6회차',
    time: '17:00 — 19:00',
    place: '나혜석거리 인근',
    title: '무엇이든 말할 수 있는 광장',
    body: '정해진 답보다 시민 각자의 목소리를 존중하는 여섯 번째 수원 행동을 열었습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DaxpHAskiKm',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-06-main.jpeg', width: 360, height: 510, alt: '공정선거 재선거 당일투표 수개표 시민행동 6회차 포스터', label: '대표 포스터' },
    ],
    photos: [
      { src: '/images/history/session-06/field-01.webp', width: 739, height: 1600, alt: '공정선거 시민행동 6회차 현장에 준비된 간식', label: '현장 간식' },
      { src: '/images/history/session-06/field-02.webp', width: 1600, height: 1200, alt: '여름 광장을 위해 준비한 음료와 물', label: '여름 광장 준비' },
      { src: '/images/history/session-06/field-03.webp', width: 1600, height: 1200, alt: '태극 문양 옷을 맞춰 입은 가족 참가자들', label: '가족 참가자' },
      { src: '/images/history/session-06/field-04.webp', width: 1200, height: 1600, alt: '나혜석거리 분수 앞 시민행동 부스와 참가자들', label: '6회차 현장' },
    ],
  },
  {
    date: '2026. 07. 25',
    session: '7회차',
    time: '17:00 — 19:00',
    place: '인계동 나혜석거리',
    title: '낮과 밤, 함께 만드는 일곱 번째 광장',
    body: '가족이 함께하는 낮의 활기와 청년이 연결되는 밤의 에너지를 담은 두 시안으로 일곱 번째 수원 행동을 알렸습니다.',
    link: 'https://www.threads.com/@fairly_evenly?hl=ko',
    source: '전시언 공식 Threads',
    posters: [
      { src: '/images/posters/suwon-action-07-day.jpeg', width: 1024, height: 1535, alt: '가족이 수박을 나누는 공정선거 시민행동 7회차 낮 포스터', label: '낮 시안' },
      { src: '/images/posters/suwon-action-07-night.jpeg', width: 1024, height: 1536, alt: '시민들이 응원봉을 든 공정선거 시민행동 7회차 밤 포스터', label: '밤 시안' },
    ],
    photos: [
      { src: '/images/history/session-07/field-01.webp', width: 1600, height: 1200, alt: '태극기와 손팻말을 든 공정선거 시민행동 7회차 참가자들', label: '7회차 광장' },
      { src: '/images/history/session-07/field-02.webp', width: 1600, height: 1200, alt: '나혜석거리 천막 아래에서 시민과 대화하는 참가자들', label: '시민과의 대화' },
      { src: '/images/history/session-07/field-03.webp', width: 1600, height: 1200, alt: '테이블에서 현장 참여 안내를 진행하는 모습', label: '참여 안내' },
    ],
  },
];

export const olgongTwoCut = {
  eyebrow: 'A NEW WAY TO GATHER',
  title: '사진을 찍는 순간만큼은 웃을 수 있게',
  summary: '올공두컷은 현장 부스에서 시작해, 누구나 휴대폰으로 찍을 수 있는 공개 포토부스로 확장된 시민 콘텐츠입니다.',
  principle: '사진값은 돈이 아니라 서로를 달래는 말 한마디입니다. 언성이 높아지는 순간에도 심판처럼 서기보다 "괜찮아, 그 마음 이해해"라고 다독이는 평화로운 참여를 요청합니다.',
  appUrl: 'https://photobooth-ecru-phi.vercel.app',
  sourceUrl: 'https://www.threads.com/@gibalza_/post/DZyjAFyj-Rw',
  stepsUrl: 'https://www.threads.com/@gibalza_/post/DZyjAazD7sX',
  points: [
    ['OPEN', '부스 이후에도 누구나 휴대폰에서 찍을 수 있게 공개했습니다.'],
    ['PLAY', '프레임을 고르고 5장을 찍은 뒤, 마음에 드는 2장을 내려받습니다.'],
    ['PEACE', '밝은 사진 한 장으로 현장의 긴장을 낮추는 참여 문화를 만듭니다.'],
  ],
};

const pressVisuals = {
  'https://n.news.naver.com/article/003/0014004541': {
    image: '/images/news/suwon-olympic-park-crowd.webp',
    imageAlt: '수원 올림픽공원 산책로를 따라 함께한 공정선거 시민행동 참가자들',
    imageCredit: '공정선거시민행동 제공',
    imageFocus: 'field-crowd',
  },
  'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 올림픽공원에서 열린 재선거 촉구 집회',
    imageCredit: '동일 현장 사진 · 연합뉴스 이영주',
    imageFocus: 'speaker',
  },
  'https://www.yna.co.kr/view/AKR20260613033400061': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '유모차를 끌고 온 가족과 지역 주민들',
    imageCredit: '연합뉴스',
    imageFocus: 'speaker-center',
  },
  'https://www.yna.co.kr/view/AKR20260613033400061?amp=1': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '유모차를 끌고 온 가족과 지역 주민들',
    imageCredit: '연합뉴스',
    imageFocus: 'speaker-center',
  },
  'https://n.news.naver.com/article/437/0000496019': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 집회 현장의 시민들',
    imageCredit: '연합뉴스TV',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/016/0002656079': {
    image: '/images/news/herald-suwon.jpg',
    imageAlt: '투표용지 부족 규탄 시위 경기까지',
    imageCredit: '헤럴드경제',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/422/0000874401': {
    image: '/images/news/yonhap-tv.jpg',
    imageAlt: '연합뉴스TV 보도 현장 화면',
    imageCredit: '연합뉴스TV',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/666/0000110606': {
    image: '/images/news/kyeonggi-vote.jpg',
    imageAlt: '경기지역 투표용지 부족 관련 현장 자료',
    imageCredit: '경기일보',
    imageFocus: 'speaker',
  },
  'https://www.kgnews.co.kr/news/article.html?no=899276': {
    image: '/images/news/kgnews-vote.jpg',
    imageAlt: '경기 36곳 투표용지 비상 현장',
    imageCredit: '경기신문',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/001/0016129186': {
    image: '/images/news/yna-vote.jpg',
    imageAlt: '투표지 추가 송부와 선거인 명부 누락 관련 자료',
    imageCredit: '연합뉴스',
    imageFocus: 'speaker',
  },
  'https://www.kyeongin.com/article/1765268': {
    image: '/images/news/kyeongin-vote.jpg',
    imageAlt: '경기도 투표소 현장',
    imageCredit: '경인일보',
    imageFocus: 'speaker',
  },
  'https://www.joongang.co.kr/article/25436607': {
    image: '/images/news/joongang-action.jpg',
    imageAlt: '올공두컷 부스와 수원 집회 현장',
    imageCredit: '중앙일보',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/025/0003532986': {
    image: '/images/news/joongang-interview.jpg',
    imageAlt: '전시언 인터뷰 관련 보도 화면',
    imageCredit: '중앙일보',
    imageFocus: 'speaker',
  },
  'https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02145126645481720': {
    image: '/images/news/edaily-olgong.jpg',
    imageAlt: '잠실에서 운영된 올공네컷 시민 체험 공간',
    imageCredit: '이데일리',
    imageFocus: 'speaker',
  },
  'https://www.wikitree.co.kr/articles/1141627': {
    image: '/images/news/wikitree-olgong.jpg',
    imageAlt: '서울 올림픽공원 핸드볼경기장 앞에 모인 시민들',
    imageCredit: '위키트리',
  },
  'https://www.fnnews.com/news/202606101502443216': {
    image: '/images/news/fnnews-dashboard.png',
    imageAlt: '시민이 만든 디지털 상황판',
    imageCredit: '파이낸셜뉴스',
    imageFocus: 'speaker',
  },
  'https://naver.me/FjmwJ2Vn': {
    image: '/images/news/yna-families-main.png',
    imageAlt: '유모차부터 3대가 함께한 수원 집회 현장',
    imageCredit: '네이버링크 변환',
    imageFocus: 'speaker-center',
  },
  'https://naver.me/5B0t3BHW': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 재선거 촉구 집회 현장',
    imageCredit: '네이버링크 변환',
    imageFocus: 'speaker',
  },
};

const withPressVisual = (item) => ({ ...item, ...pressVisuals[item.href] });

export const historyEvidence = [
  {
    date: '2026. 06. 13',
    category: '현장 보도',
    relation: '1회차 · 수원 현장',
    media: '연합뉴스',
    title: '‘유모차부터 3대 가족까지’…수원서도 ‘재선거 촉구’ 집회',
    summary: '수원에서 열린 첫 집회와 가족 단위 참가자의 참여를 기록한 보도입니다.',
    href: 'https://www.yna.co.kr/view/AKR20260613033400061',
  },
  {
    date: '2026. 06. 13',
    category: '현장 보도',
    relation: '1회차 · 수원 현장',
    media: 'JTBC',
    title: '수원서도 재선거 촉구 집회…시민 40여명 “부정선거 규탄”',
    summary: '수원 집회에 이어 규탄이 확산된 모습을 다뤘습니다.',
    href: 'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html',
  },
  {
    date: '2026. 06. 13',
    category: '현장 보도',
    relation: '1회차 · 수원 올림픽공원',
    media: '뉴시스',
    title: '수원도 시민들 모여 [현장]',
    summary: '다양한 세대가 함께한 현장 기록과 집회 장면을 보여줍니다.',
    href: 'https://n.news.naver.com/article/003/0014004541',
  },
  {
    date: '2026. 06. 14',
    category: '시민 콘텐츠',
    relation: '올공두컷',
    media: '중앙일보',
    title: '朴·尹 탄핵찬성했던 청년 ‘올공두컷’ 부스 차렸다…열흘째 체육단체는 마비',
    summary: '수원 집회 현장에서 시작된 올공두컷을 중심으로 한 기록 기사입니다.',
    href: 'https://www.joongang.co.kr/article/25436607',
  },
  {
    date: '2026. 06. 25',
    category: '인터뷰',
    relation: '전시언 · 투표 연장 문제',
    media: '중앙일보',
    title: '[단독] 0분부터 240분까지…투표 멈춘 곳들 ‘연장시간 제각각’ 왜',
    summary: '투표 중단과 연장 시간 차이를 지적하며 공정성 문제를 다룬 인터뷰 기사입니다.',
    href: 'https://n.news.naver.com/article/025/0003532986',
  },
  {
    date: '2026. 06. 09',
    category: '선거 현장',
    relation: '경기권 선거',
    media: '경기일보',
    title: '경기지역서도 투표용지 부족 36개 투표소에 추가 송부',
    summary: '수원 장안·권선 포함 경기 내 추가 투표용지 송부 보도입니다.',
    href: 'https://n.news.naver.com/article/666/0000110606',
  },
  {
    date: '2026. 06. 09',
    category: '선거 현장',
    relation: '경기지역',
    media: '경기신문',
    title: '경기 36곳 투표지 비상…9년 전 고양서도 같은 혼선',
    summary: '재발 우려가 큰 투표지 비상 상황을 정리한 기사입니다.',
    href: 'https://www.kgnews.co.kr/news/article.html?no=899276',
  },
  {
    date: '2026. 06. 09',
    category: '선거 현장',
    relation: '수원 장안·권선',
    media: '연합뉴스',
    title: '경기 36개 투표소에도 투표지 추가 송부…선거인 명부 누락도',
    summary: '수원 장안 3곳·권선 1곳 사례를 포함한 추가 송부 및 누락 현황 보도입니다.',
    href: 'https://n.news.naver.com/article/001/0016129186',
  },
].map(withPressVisual);

export const organization = [
  ['01', '현장행동', '집회 · 캠페인'],
  ['02', '자료검증', '조사 · 팩트체크'],
  ['03', '콘텐츠', '기록 · 확산'],
  ['04', '시민연대', '교육 · 네트워크'],
];

export const reports = [
  {
    category: '수원 현장',
    media: '연합뉴스',
    date: '2026. 06. 13',
    title: '‘유모차부터 3대 가족까지’…수원서도 ‘재선거 촉구’ 집회',
    summary: '수원 올림픽공원에 모인 가족 단위 참가자와 시민들의 참여를 기록한 현장 보도입니다.',
    href: 'https://www.yna.co.kr/view/AKR20260613033400061',
  },
  {
    category: '수원 현장',
    media: '뉴시스',
    date: '2026. 06. 13',
    title: '‘부정선거 재선거’ 유모차 끌고, 돗자리 깔고…수원도 시민들 모여[현장]',
    summary: '올림픽공원 현장의 가족 단위 참여와 현장 동학을 담았습니다.',
    href: 'https://n.news.naver.com/article/003/0014004541',
  },
  {
    category: '수원 현장',
    media: 'JTBC',
    date: '2026. 06. 13',
    title: '수원서도 재선거 촉구 집회…시민 40여명 규탄',
    summary: '현장 집회와 시민 참여 분위기를 다뤘습니다.',
    href: 'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html',
  },
  {
    category: '수원 현장',
    media: 'JTBC',
    date: '2026. 06. 13',
    title: '수원까지 번진 재선거 촉구 집회',
    summary: '수원 일대의 연대 확산을 중심으로 한 보도입니다.',
    href: 'https://n.news.naver.com/article/437/0000496019',
  },
  {
    category: '관련 보도',
    media: '헤럴드경제',
    date: '2026. 06. 13',
    title: '투표용지 부족 규탄 시위 경기까지 확산',
    summary: '수원권 집회와 경기 지역 확산 보도를 함께 정리한 기사입니다.',
    href: 'https://n.news.naver.com/article/016/0002656079',
  },
  {
    category: '관련 보도',
    media: '연합뉴스',
    date: '2026. 06. 13',
    title: '[뉴스1번지] 투표지 부족 관련 발표와 규탄',
    summary: '투표지 부족 보도 속 수원 집회 언급을 함께 다루었습니다.',
    href: 'https://n.news.naver.com/article/422/0000874401',
  },
  {
    category: '단체·인물',
    project: 'olgong',
    media: '중앙일보',
    date: '2026. 06. 14',
    title: '朴·尹 탄핵찬성했던 청년 ‘올공두컷’ 부스 차렸다…열흘째 체육단체는 마비',
    summary: '수원 1회차 집회와 올공두컷 현장 조각을 함께 담았습니다.',
    href: 'https://www.joongang.co.kr/article/25436607',
  },
  {
    category: '인터뷰',
    media: '중앙일보',
    date: '2026. 06. 25',
    title: '[단독] 0분부터 240분까지…투표 멈춘 곳들 시간 기준',
    summary: '확대 적용 시점의 시간 기준을 짚은 인터뷰형 기사입니다.',
    href: 'https://n.news.naver.com/article/025/0003532986',
  },
  {
    category: '현장 콘텐츠',
    project: 'olgong',
    media: '이데일리',
    date: '2026. 06. 14',
    title: '‘잠실 개표소 시위’서 무료 과외·올공네컷 등 이색 체험존 등장…경찰은 장기전 대비',
    summary: 'AI로 프레임을 제작하고 현장 프린터로 사진을 제공한 올공두컷 체험존을 소개했습니다.',
    href: 'https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02145126645481720',
  },
  {
    category: '현장 콘텐츠',
    project: 'olgong',
    media: '위키트리',
    date: '2026. 06. 17',
    title: '아기띠 둘러메고 커플끼리 손잡고…시민 발길 이어진 올림픽공원 속 목소리 [르포]',
    summary: '가족·청년 참가자와 자원봉사 현장을 취재하며 즉석사진을 인화해 주는 올공두컷을 함께 소개했습니다.',
    href: 'https://www.wikitree.co.kr/articles/1141627',
  },
  {
    category: '시민 기술',
    media: '파이낸셜뉴스',
    date: '2026. 06. 10',
    title: '시민이 직접 만든 디지털 상황판',
    summary: '집회 정보와 현장 상황을 연결한 시민 기술 보도입니다.',
    href: 'https://www.fnnews.com/news/202606101502443216',
  },
  {
    category: '수원 현장',
    media: '연합뉴스',
    date: '2026. 06. 13',
    title: '수원 집회 네트워킹 참여 안내(요약)',
    summary: '네이버 링크 기반으로 수집한 집회 보도 원문을 함께 제공합니다.',
    href: 'https://naver.me/FjmwJ2Vn',
  },
  {
    category: '수원 현장',
    media: 'JTBC',
    date: '2026. 06. 13',
    title: '수원 재선거 촉구 집회 참여 증가 현장 보도(요약)',
    summary: '네이버 링크 기반으로 시민 확산 보도 원문을 함께 제공합니다.',
    href: 'https://naver.me/5B0t3BHW',
  },
].map(withPressVisual);
