export const actions = [
  {
    number: '01',
    title: '현장 감시와 기록',
    description: '투·개표 과정과 시민의 목소리를 현장에서 관찰하고 출처가 남는 기록으로 정리합니다.',
    tag: 'WATCH',
  },
  {
    number: '02',
    title: '정보 검증과 공유',
    description: '공개 자료와 언론 보도를 교차 확인해 누구나 따라갈 수 있는 근거로 나눕니다.',
    tag: 'VERIFY',
  },
  {
    number: '03',
    title: '평화로운 시민행동',
    description: '집회, 캠페인, 공론장을 통해 안전하고 질서 있는 참여의 장을 만듭니다.',
    tag: 'ACT',
  },
  {
    number: '04',
    title: '시민 교육과 연대',
    description: '세대와 지역을 넘어 건강한 민주시민 문화를 함께 키웁니다.',
    tag: 'CONNECT',
  },
];

export const timeline = [
  {
    date: '2026. 06. 13',
    session: '1회차',
    time: '10:00 — 18:00',
    place: '수원 올림픽공원',
    title: '수원에서 시작된 첫 시민행동',
    body: '가족과 청년, 어르신이 함께한 첫 광장입니다. 오전 현장 약 40명, 하루 누적 약 300명으로 시점별 집계가 언론에 보도됐습니다.',
    link: 'https://www.joongang.co.kr/article/25436607',
    source: '중앙일보 현장 보도',
    posters: [
      { src: '/images/posters/suwon-action-01-main.jpeg', width: 360, height: 540, alt: '공정선거 시민행동 수원 첫 집회 재선거 포스터', label: '첫 집회 포스터' },
    ],
  },
  {
    date: '2026. 06. 20',
    session: '2회차',
    time: '16:00 — 18:00',
    place: '인계동 나혜석거리',
    title: '각자의 목소리를 내는 자리',
    body: '경기 남부 시민들이 더 가까운 곳에서 참여할 수 있도록 나혜석거리로 자리를 옮겼습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DZsEGjSEmTM',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-02-main.jpeg', width: 1024, height: 1536, alt: '아이들의 미래를 지킬 공정선거 시민행동 2회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-02-mothers.jpeg', width: 360, height: 540, alt: '수원 엄마들의 재선거 촉구 2회차 포스터', label: '엄마들' },
      { src: '/images/posters/suwon-action-02-youth.jpeg', width: 360, height: 540, alt: '수원 청년들의 공정선거 시민행동 2회차 포스터', label: '청년들' },
      { src: '/images/posters/suwon-action-02-green.jpeg', width: 360, height: 540, alt: '참정권 수호 공정선거 시민행동 2회차 초록 포스터', label: '참정권 수호' },
      { src: '/images/posters/suwon-action-02-red.jpeg', width: 360, height: 540, alt: '공정선거 시민행동 2회차 붉은 포스터', label: '공정선거' },
      { src: '/images/posters/suwon-action-02-pink.jpeg', width: 360, height: 540, alt: '수원 엄마들이 일어납니다 2회차 포스터', label: '수원 엄마들' },
    ],
  },
  {
    date: '2026. 06. 27',
    session: '3회차',
    time: '16:00 — 18:00',
    place: '인계동 나혜석거리',
    title: '매주 이어지는 지역의 목소리',
    body: '두 번째 행동에 이어 같은 장소에서 시민의 질문과 목소리를 모았습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DZ2gl9CEng8',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-03-main.jpeg', width: 360, height: 540, alt: '엄마 아빠도 그때 함께 했어 공정선거 시민행동 3회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-03-invitation.jpeg', width: 360, height: 510, alt: '공정선거 시민행동 3회차 흑백 초대장 포스터', label: '초대장' },
    ],
  },
  {
    date: '2026. 07. 04',
    session: '4회차',
    time: '17:00 — 19:00',
    place: '인계동 나혜석거리',
    title: '여름 저녁으로 시간을 옮기다',
    body: '여름 날씨에 맞춰 시간을 오후 5시로 변경하고 공개 채팅으로 참여 안내를 이어갔습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DaK0YJbEmHt',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-04-main.jpeg', width: 360, height: 510, alt: '6월 3일 이후 시간이 멈췄습니다 공정선거 시민행동 4회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-04-sunset.jpeg', width: 360, height: 510, alt: '자유민주주의 시간이 멈췄습니다 공정선거 시민행동 4회차 포스터', label: '태극기 시안' },
    ],
  },
  {
    date: '2026. 07. 11',
    session: '5회차',
    time: '17:00 — 19:00',
    place: '나혜석거리 인근',
    title: '비가 와도 이어진 다섯 번째 행동',
    body: '우천 안내와 준비 인원 모집을 공개하고 지역 상점 이용을 함께 요청했습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/Dac_eoAEvX-',
    source: '전시언 Threads 공지',
    posters: [
      { src: '/images/posters/suwon-action-05-main.jpeg', width: 360, height: 540, alt: '무엇이든 말하고 싶습니다 공정선거 시민행동 5회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-05-crowd.jpeg', width: 360, height: 540, alt: '공정선거 재선거 당일투표 수개표 시민행동 5회차 포스터', label: '현장 시안' },
    ],
  },
  {
    date: '2026. 07. 18',
    session: '6회차',
    time: '17:00 — 19:00',
    place: '나혜석거리 인근',
    title: '무엇이든 말할 수 있는 광장',
    body: '정해진 답보다 시민 각자의 목소리를 존중하는 여섯 번째 수원 행동을 열었습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DaxpHAskiKm',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-06-main.jpeg', width: 360, height: 510, alt: '공정선거 재선거 당일투표 수개표 시민행동 6회차 포스터', label: '대표 포스터' },
    ],
  },
];

export const olgongTwoCut = {
  eyebrow: 'A NEW WAY TO GATHER',
  title: '사진을 찍는 순간만큼은 웃을 수 있게',
  summary: '올공두컷은 현장 부스에서 시작해, 누구나 휴대폰으로 찍을 수 있는 공개 포토부스로 확장된 시민 콘텐츠입니다. 분노만 남는 광장이 아니라 가족과 친구가 함께 웃는 기억도 남기자는 마음을 담았습니다.',
  principle: '사진값은 돈이 아니라 서로를 달래는 말 한마디입니다. 언성이 높아지는 순간에도 심판처럼 서기보다 “괜찮아, 그 마음 이해해”라고 다독이는 평화로운 참여를 요청합니다.',
  appUrl: 'https://photobooth-ecru-phi.vercel.app',
  sourceUrl: 'https://www.threads.com/@gibalza_/post/DZyjAFyj-Rw',
  stepsUrl: 'https://www.threads.com/@gibalza_/post/DZyjAazD7sX',
  points: [
    ['OPEN', '부스 이후에도 누구나 휴대폰에서 찍을 수 있게 공개했습니다.'],
    ['PLAY', '프레임을 고르고 5장을 찍은 뒤, 마음에 드는 2장을 내려받습니다.'],
    ['PEACE', '밝은 사진 한 장으로 현장의 긴장을 낮추는 참여 문화를 만듭니다.'],
  ],
};

const pressVisuals = {
  'https://n.news.naver.com/article/003/0014004541': {
    image: '/images/news/newsis-suwon-speaker.jpg',
    imageAlt: '수원 올림픽공원 집회에서 시민들 앞에 선 남성',
    imageCredit: '뉴시스 기사 대표 이미지',
    imageFocus: 'speaker',
  },
  'https://www.yna.co.kr/view/AKR20260613033400061': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 올림픽공원에서 열린 재선거 촉구 집회',
    imageCredit: '연합뉴스 · 촬영 이영주',
  },
  'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 올림픽공원에서 열린 재선거 촉구 집회',
    imageCredit: '동일 현장 사진 · 연합뉴스 이영주',
  },
  'https://n.news.naver.com/article/437/0000496019': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 올림픽공원에서 열린 재선거 촉구 집회',
    imageCredit: '동일 현장 사진 · 연합뉴스 이영주',
  },
  'https://n.news.naver.com/article/016/0002656079': {
    image: '/images/news/herald-suwon.jpg',
    imageAlt: '투표용지 부족 규탄 집회 현장',
    imageCredit: '헤럴드경제 기사 대표 이미지',
  },
  'https://n.news.naver.com/article/422/0000874401': {
    image: '/images/news/yonhap-tv.jpg',
    imageAlt: '투표용지 부족 관련 연합뉴스TV 보도 화면',
    imageCredit: '연합뉴스TV 기사 대표 이미지',
  },
  'https://n.news.naver.com/article/666/0000110606': {
    image: '/images/news/kyeonggi-vote.jpg',
    imageAlt: '경기지역 투표용지 부족 관련 보도 이미지',
    imageCredit: '경기일보 기사 대표 이미지',
  },
  'https://www.kgnews.co.kr/news/article.html?no=899276': {
    image: '/images/news/kgnews-vote.jpg',
    imageAlt: '경기도 투표용지 추가 송부 현황 자료',
    imageCredit: '경기신문 기사 대표 이미지',
  },
  'https://n.news.naver.com/article/001/0016129186': {
    image: '/images/news/yna-vote.jpg',
    imageAlt: '투표용지 부족 관련 선거 현장 자료 이미지',
    imageCredit: '연합뉴스 기사 대표 이미지',
  },
  'https://www.kyeongin.com/article/1765268': {
    image: '/images/news/kyeongin-vote.jpg',
    imageAlt: '투표용지 부족 관련 투표소 현장',
    imageCredit: '경인일보 기사 대표 이미지',
  },
  'https://www.joongang.co.kr/article/25436607': {
    image: '/images/news/joongang-action.jpg',
    imageAlt: '시민 집회 현장에서 운영된 올공두컷',
    imageCredit: '중앙일보 기사 대표 이미지',
  },
  'https://n.news.naver.com/article/025/0003532986': {
    image: '/images/news/joongang-interview.jpg',
    imageAlt: '투표 중단 및 연장시간 관련 현장 자료 이미지',
    imageCredit: '중앙일보 기사 대표 이미지',
  },
  'https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02145126645481720': {
    image: '/images/news/edaily-olgong.jpg',
    imageAlt: '잠실 현장의 올공네컷 시민 체험 공간',
    imageCredit: '이데일리 기사 대표 이미지',
  },
  'https://www.fnnews.com/news/202606101502443216': {
    image: '/images/news/fnnews-dashboard.png',
    imageAlt: '시민이 만든 잠실 현장 디지털 상황판',
    imageCredit: '파이낸셜뉴스 기사 대표 이미지',
  },
};

const withPressVisual = (item) => ({ ...item, ...pressVisuals[item.href] });

export const historyEvidence = [
  {
    date: '2026. 06. 08',
    category: '선거 현장',
    relation: '경기도 · 수원 장안·권선',
    media: '경인일보',
    title: '경기도도 투표용지 부족 23곳… 김포에선 투표 중단',
    summary: '경기도 투표소의 투표용지 부족 현황을 다루며 수원 장안구와 권선구 사례를 포함한 기사입니다.',
    href: 'https://www.kyeongin.com/article/1765268',
  },
  {
    date: '2026. 06. 09',
    category: '선거 현장',
    relation: '경기도 36개 투표소 · 수원 포함',
    media: '경기일보',
    title: '경기지역서도 투표용지 부족 확인…36개 투표소에 추가 송부',
    summary: '경기도 내 추가 투표용지 송부 현황과 수원 장안·권선 지역 사례를 정리한 보도입니다.',
    href: 'https://n.news.naver.com/article/666/0000110606',
  },
  {
    date: '2026. 06. 09',
    category: '선거 현장',
    relation: '경기 36곳 · 수원 장안·권선',
    media: '경기신문',
    title: '경기 36곳 ‘투표용지 비상’…9년 전 고양서도 같은 혼선',
    summary: '경기도 36개 투표소의 추가 송부와 실제 사용 현황을 다루며 수원 장안구 3곳과 권선구 1곳 사례를 포함했습니다.',
    href: 'https://www.kgnews.co.kr/news/article.html?no=899276',
  },
  {
    date: '2026. 06. 09',
    category: '선거 현장',
    relation: '경기 36곳 · 수원 4곳',
    media: '연합뉴스',
    title: '경기 36개 투표소에도 투표지 추가 송부…선거인 명부 누락도(종합)',
    summary: '수원 장안 3곳과 권선 1곳을 포함한 경기도 투표용지 추가 송부 현황과 실제 사용 사례를 구체적으로 보도했습니다.',
    href: 'https://n.news.naver.com/article/001/0016129186',
  },
  {
    date: '2026. 06. 13',
    category: '수원 현장',
    relation: '1회차 · 가족과 시민 참여',
    media: '연합뉴스',
    title: '‘유모차부터 3대 가족까지’…수원서도 ‘재선거 촉구’ 집회',
    summary: '수원 올림픽공원에서 열린 첫 집회와 유모차·3대 가족 등 다양한 세대의 참여를 취재했습니다.',
    href: 'https://www.yna.co.kr/view/AKR20260613033400061',
  },
  {
    date: '2026. 06. 13',
    category: '수원 현장',
    relation: '1회차 · 현장 약 40명',
    media: 'TV조선',
    title: '수원서도 재선거 촉구 집회…시민 40여명 “부정선거 규탄”',
    summary: '수원에서 열린 재선거 촉구 집회와 보도 시점 기준 시민 약 40명의 참여를 전했습니다.',
    href: 'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html',
  },
  {
    date: '2026. 06. 13',
    category: '수원 현장',
    relation: '1회차 · 올림픽공원',
    media: '뉴시스',
    title: '‘부정선거 재선거’ 유모차 끌고, 돗자리 깔고…수원도 시민들 모여[현장]',
    summary: '수원 올림픽공원에 모인 시민과 가족 단위 참가자의 현장 모습을 기록한 기사입니다.',
    href: 'https://n.news.naver.com/article/003/0014004541',
  },
  {
    date: '2026. 06. 13',
    category: '수원 현장',
    relation: '1회차 · 현장 약 50명',
    media: 'JTBC',
    title: '수원까지 번진 ‘재선거 촉구’ 집회…시민 50여 명 참여',
    summary: '수원 올림픽공원 집회와 보도 시점 기준 시민 약 50명의 참여를 다뤘습니다.',
    href: 'https://n.news.naver.com/article/437/0000496019',
  },
  {
    date: '2026. 06. 13',
    category: '지역 확산',
    relation: '수원 권선구 올림픽공원',
    media: '헤럴드경제',
    title: '투표용지 부족 규탄 시위 경기까지…이수정 교수도 “재선거해야” 가세',
    summary: '투표용지 부족 문제에 대한 집회가 수원 등 경기 지역으로 확산된 흐름을 보도했습니다.',
    href: 'https://n.news.naver.com/article/016/0002656079',
  },
  {
    date: '2026. 06. 13',
    category: '관련 보도',
    relation: '수원 집회 언급',
    media: '연합뉴스TV',
    title: '[뉴스1번지] ‘투표지 부족’ 수사 속도…張, 재선거 공개 제안',
    summary: '투표용지 부족 논란과 재선거 요구 흐름을 다루며 수원 집회 개최 사실을 함께 언급했습니다.',
    href: 'https://n.news.naver.com/article/422/0000874401',
  },
  {
    date: '2026. 06. 14',
    category: '현장 보도',
    relation: '1회차 수원 집회 · 올공두컷',
    media: '중앙일보',
    title: '朴·尹 탄핵찬성했던 청년 ‘올공두컷’ 부스 차렸다…열흘째 체육단체는 마비',
    summary: '수원 올림픽공원 1회차 집회와 주최자 전시언, 잠실 현장에서 시작된 올공두컷을 함께 기록한 기사입니다.',
    href: 'https://www.joongang.co.kr/article/25436607',
  },
  {
    date: '2026. 06. 25',
    category: '언론 인터뷰',
    relation: '전시언 · 투표 중단과 연장시간',
    media: '중앙일보',
    title: '[단독] 0분부터 240분까지…투표 멈춘 곳들 ‘연장시간 제각각’ 왜',
    summary: '투표 중단 시간과 연장시간의 기준이 달랐던 문제를 다룬 기사로, 전시언은 멈춘 시간만큼 투표 기회가 보장되어야 한다는 취지로 말했습니다.',
    href: 'https://n.news.naver.com/article/025/0003532986',
  },
].map(withPressVisual);

export const organization = [
  ['01', '현장행동', '집회 · 캠페인'],
  ['02', '자료검증', '조사 · 팩트체크'],
  ['03', '콘텐츠', '기록 · 확산'],
  ['04', '시민연대', '교육 · 네트워크'],
];

export const reports = [
  {
    category: '수원 현장',
    media: '뉴시스',
    date: '2026. 06. 13',
    title: '‘부정선거 재선거’ 유모차 끌고, 돗자리 깔고…수원도 시민들 모여[현장]',
    summary: '오전 10시 무렵 수원 올림픽공원에 모인 약 40명의 시민과 다양한 세대의 참여를 취재했습니다.',
    href: 'https://n.news.naver.com/article/003/0014004541',
  },
  {
    category: '수원 현장',
    media: '연합뉴스',
    date: '2026. 06. 13',
    title: '‘유모차부터 3대 가족까지’…수원서도 ‘재선거 촉구’ 집회',
    summary: '온라인 게시물을 보고 모인 시민과 가족 단위 참여를 오전 현장 기준으로 보도했습니다.',
    href: 'https://www.yna.co.kr/view/AKR20260613033400061',
  },
  {
    category: '수원 현장',
    media: 'TV조선',
    date: '2026. 06. 13',
    title: '수원서도 재선거 촉구 집회…시민 40여명 “부정선거 규탄”',
    summary: '수원 집회와 보도 시점 기준 시민 약 40명의 참여를 전했습니다.',
    href: 'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html',
  },
  {
    category: '수원 현장',
    media: 'JTBC',
    date: '2026. 06. 13',
    title: '수원까지 번진 ‘재선거 촉구’ 집회…시민 50여 명 참여',
    summary: '수원 올림픽공원 집회와 보도 시점 기준 시민 약 50명의 참여를 다뤘습니다.',
    href: 'https://n.news.naver.com/article/437/0000496019',
  },
  {
    category: '지역 확산',
    media: '헤럴드경제',
    date: '2026. 06. 13',
    title: '투표용지 부족 규탄 시위 경기까지…이수정 교수도 “재선거해야” 가세',
    summary: '수원 권선구 올림픽공원 집회를 포함해 경기 지역으로 확산된 흐름을 보도했습니다.',
    href: 'https://n.news.naver.com/article/016/0002656079',
  },
  {
    category: '관련 보도',
    media: '연합뉴스TV',
    date: '2026. 06. 13',
    title: '[뉴스1번지] ‘투표지 부족’ 수사 속도…張, 재선거 공개 제안',
    summary: '투표용지 부족 논란을 다루며 수원에서 열린 재선거 촉구 집회를 언급했습니다.',
    href: 'https://n.news.naver.com/article/422/0000874401',
  },
  {
    category: '선거 현장',
    media: '경기일보',
    date: '2026. 06. 09',
    title: '경기지역서도 투표용지 부족 확인…36개 투표소에 추가 송부',
    summary: '경기도 36개 투표소의 추가 송부 현황과 수원 장안·권선 지역 사례를 정리했습니다.',
    href: 'https://n.news.naver.com/article/666/0000110606',
  },
  {
    category: '선거 현장',
    media: '경기신문',
    date: '2026. 06. 09',
    title: '경기 36곳 ‘투표용지 비상’…9년 전 고양서도 같은 혼선',
    summary: '경기도 36개 투표소의 추가 송부 현황과 수원 장안구 3곳·권선구 1곳 사례를 포함했습니다.',
    href: 'https://www.kgnews.co.kr/news/article.html?no=899276',
  },
  {
    category: '선거 현장',
    media: '연합뉴스',
    date: '2026. 06. 09',
    title: '경기 36개 투표소에도 투표지 추가 송부…선거인 명부 누락도(종합)',
    summary: '수원 장안 3곳과 권선 1곳을 포함한 경기도 투표용지 추가 송부 및 실제 사용 현황을 보도했습니다.',
    href: 'https://n.news.naver.com/article/001/0016129186',
  },
  {
    category: '선거 현장',
    media: '경인일보',
    date: '2026. 06. 08',
    title: '경기도도 투표용지 부족 23곳… 김포에선 투표 중단',
    summary: '경기도 내 투표용지 부족 현황을 보도하며 수원 장안구와 권선구 사례를 포함했습니다.',
    href: 'https://www.kyeongin.com/article/1765268',
  },
  {
    category: '단체·인물',
    media: '중앙일보',
    date: '2026. 06. 14',
    title: '朴·尹 탄핵찬성했던 청년 ‘올공두컷’ 부스 차렸다…열흘째 체육단체는 마비',
    summary: '수원 집회의 주최, 8시간 누적 약 300명의 참여, 올공두컷 현장 콘텐츠를 함께 소개했습니다.',
    href: 'https://www.joongang.co.kr/article/25436607',
  },
  {
    category: '인터뷰',
    media: '중앙일보',
    date: '2026. 06. 25',
    title: '[단독] 0분부터 240분까지…투표 멈춘 곳들 ‘연장시간 제각각’ 왜',
    summary: '투표 중단 시간과 연장시간의 기준 차이를 다루며 공정선거 시민행동 전시언의 발언을 인용했습니다.',
    href: 'https://n.news.naver.com/article/025/0003532986',
  },
  {
    category: '현장 콘텐츠',
    media: '이데일리',
    date: '2026. 06. 14',
    title: '가족이 함께한 광장, 올공두컷이 남긴 장면',
    summary: 'AI로 만든 프레임과 즉석 출력 장비를 활용한 올공두컷 운영 과정을 소개했습니다.',
    href: 'https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02145126645481720',
  },
  {
    category: '시민 기술',
    media: '파이낸셜뉴스',
    date: '2026. 06. 10',
    title: '시민이 직접 만든 디지털 상황판',
    summary: '집회 정보와 현장 상황을 시민 기술로 연결한 디지털 도구를 다뤘습니다.',
    href: 'https://www.fnnews.com/news/202606101502443216',
  },
].map(withPressVisual);
