export const brandRelationship = '경기우파청년들은 상위 단체이며, 공정선거시민행동은 경기우파청년들의 첫 시민행동입니다.';

export const nextAction = {
  status: 'preparing',
  label: '다음 일정 준비 중',
  title: '다음 현장 일정을 준비하고 있습니다.',
  description: '새 일정은 공식 Threads와 팀채팅방에서 가장 먼저 안내합니다.',
};

export const participationWays = [
  {
    id: 'field',
    number: '01',
    title: '현장 참여',
    summary: '집회, 캠페인, 공론장에서 질서 있는 참여의 장을 함께 만듭니다.',
    forWhom: '현장에서 직접 목소리를 듣고 행동을 함께하고 싶은 시민',
    preparation: '공지된 날짜와 장소를 확인하고 편한 복장으로 참여합니다.',
    nextStep: '팀채팅방에서 다음 일정과 현장 안내를 확인합니다.',
  },
  {
    id: 'operations',
    number: '02',
    title: '운영 지원',
    summary: '현장 준비, 안내, 기록과 확산에 필요한 역할을 함께 나눕니다.',
    forWhom: '준비와 운영, 기록을 자신의 방식으로 돕고 싶은 시민',
    preparation: '가능한 시간과 맡고 싶은 역할을 정리합니다.',
    nextStep: '팀채팅방에서 운영진에게 가능한 역할을 알립니다.',
  },
  {
    id: 'updates',
    number: '03',
    title: '소식 확인',
    summary: '행동과 기록을 확인하고 필요한 자료를 주변과 나눕니다.',
    forWhom: '먼저 활동을 지켜보고 다음 기회를 확인하고 싶은 시민',
    preparation: '공식 Threads의 활동 기록과 일정 공지를 확인합니다.',
    nextStep: '참여할 준비가 되면 팀채팅방에서 다음 행동을 확인합니다.',
  },
];

export const actions = [
  {
    number: '01',
    title: '감시와 기록',
    description: '현장을 찾아가고 보고 듣고 기록합니다.',
    tag: 'WATCH',
  },
  {
    number: '02',
    title: '검증과 공유',
    description: '기록과 보도, SNS를 교차 검증하고 퍼나릅니다.',
    tag: 'VERIFY',
  },
  {
    number: '03',
    title: '행동과 참여',
    description: '집회, 캠페인, 공론장을 통해 질서 있는 참여의 장을 만듭니다.',
    tag: 'ACT',
  },
  {
    number: '04',
    title: '확산과 연대',
    description: '경계를 넘어 건강한 자유민주시민으로 거듭납니다.',
    tag: 'CONNECT',
  },
];

export const timeline = [
  {
    date: '2026. 06. 13',
    session: '1회차',
    time: '10:00 — 18:00',
    place: '수원 올림픽공원',
    title: '수원에서 시작된 첫 시민행동',
    body: '가족과 청년, 어르신이 함께한 첫 광장입니다. 오전 현장 약 40명, 하루 누적 약 300명으로 언론에 보도됐습니다.',
    reportIds: ['joongang-olgong-20260614'],
    posters: [
      { src: '/images/posters/suwon-action-01-main.jpeg', width: 360, height: 540, alt: '올림픽공원 1회차 집회 포스터', label: '첫 집회 포스터' },
    ],
    photos: [
      { src: '/images/history/session-01/field-01.webp', width: 1600, height: 1200, alt: '수원 올림픽공원에 모인 1회차 시민행동 참가자들', label: '올림픽공원 전경' },
      { src: '/images/history/session-01/field-02.webp', width: 1600, height: 1200, alt: '태극기를 든 시민들이 함께한 수원 올림픽공원 집회 현장', label: '시민 참여 현장' },
      { src: '/images/history/session-01/field-03.webp', width: 1600, height: 1200, alt: '수원 올림픽공원 산책로를 따라 선 1회차 참가자들', label: '첫 행동의 광장' },
      { src: '/images/history/session-01/field-04.webp', width: 768, height: 230, alt: '수원 올림픽공원 1회차 시민행동의 여러 순간을 모은 현장 기록', label: '첫 행동 모아보기' },
    ],
  },
  {
    date: '2026. 06. 20',
    session: '2회차',
    time: '16:00 — 18:00',
    place: '인계동 나혜석거리',
    title: '각자의 목소리를 내는 자리',
    body: '경기 남부 시민들이 더 가까운 곳에서 참여할 수 있도록 나혜석거리로 자리를 옮겼습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DZsEGjSEmTM',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-02-main.jpeg', width: 1024, height: 1536, alt: '아이들의 미래를 지킬 공정선거 시민행동 2회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-02-mothers.jpeg', width: 360, height: 540, alt: '수원 엄마들의 재선거 촉구 2회차 포스터', label: '엄마들' },
      { src: '/images/posters/suwon-action-02-youth.jpeg', width: 360, height: 540, alt: '수원 청년들의 공정선거 시민행동 2회차 포스터', label: '청년들' },
      { src: '/images/posters/suwon-action-02-green.jpeg', width: 360, height: 540, alt: '참정권 수호 공정선거 시민행동 2회차 초록 포스터', label: '참정권 수호' },
      { src: '/images/posters/suwon-action-02-red.jpeg', width: 360, height: 540, alt: '공정선거 시민행동 2회차 붉은 포스터', label: '공정선거' },
      { src: '/images/posters/suwon-action-02-pink.jpeg', width: 360, height: 540, alt: '수원 엄마들이 일어납니다 2회차 포스터', label: '수원 엄마들' },
    ],
    photos: [
      { src: '/images/history/session-02/field-01.webp', width: 1600, height: 746, alt: '비가 내리는 나혜석거리에서 현수막을 든 2회차 참가자들', label: '우중 시민행동' },
      { src: '/images/history/session-02/field-02.webp', width: 1600, height: 746, alt: '천막 아래에서 이어진 수원 공정선거 시민행동 2회차', label: '천막 현장' },
      { src: '/images/history/session-02/field-03.webp', width: 1600, height: 746, alt: '우비와 태극기를 준비한 나혜석거리 참가자들', label: '비를 맞은 광장' },
      { src: '/images/history/session-02/field-04.webp', width: 1600, height: 901, alt: '비 오는 나혜석거리 천막 앞에 모인 시민들', label: '2회차 단체 기록' },
      { src: '/images/history/session-02/field-05.webp', width: 1920, height: 895, alt: '우비를 입고 나혜석거리 천막 앞에 선 2회차 참가자들', label: '우비를 입은 시민들' },
      { src: '/images/history/session-02/field-06.webp', width: 1920, height: 895, alt: '태극기와 현수막을 들고 우중 행동을 이어가는 시민들', label: '태극기와 현수막' },
      { src: '/images/history/session-02/field-07.webp', width: 1920, height: 895, alt: '비가 내리는 나혜석거리 광장에 모인 2회차 시민행동 참가자들', label: '비 내리는 광장' },
      { src: '/images/history/session-02/field-08.webp', width: 1920, height: 895, alt: '빗속 천막과 거리에서 참여를 이어간 2회차 현장', label: '천막 너머의 현장' },
      { src: '/images/history/session-02/field-09.webp', width: 1920, height: 895, alt: '우산과 우비를 준비해 공정선거 메시지를 알린 시민들', label: '우산 아래의 행동' },
      { src: '/images/history/session-02/field-10.webp', width: 768, height: 690, alt: '수원 공정선거 시민행동 2회차 우중 현장 사진 모음', label: '2회차 모아보기' },
    ],
  },
  {
    date: '2026. 06. 27',
    session: '3회차',
    time: '16:00 — 18:00',
    place: '인계동 나혜석거리',
    title: '매주 이어지는 지역의 목소리',
    body: '두 번째 행동에 이어 같은 장소에서 시민의 질문과 목소리를 모았습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DZ2gl9CEng8',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-03-main.jpeg', width: 360, height: 540, alt: '엄마 아빠도 그때 함께 했어 공정선거 시민행동 3회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-03-invitation.jpeg', width: 360, height: 510, alt: '공정선거 시민행동 3회차 흑백 초대장 포스터', label: '초대장' },
    ],
    photos: [
      { src: '/images/history/session-03/field-01.webp', width: 1600, height: 746, alt: '나혜석거리 천막 앞에서 발언하는 3회차 참가자', label: '시민 발언' },
      { src: '/images/history/session-03/field-02.webp', width: 1600, height: 746, alt: '태극기가 걸린 수원 공정선거 시민행동 부스', label: '시민행동 부스' },
      { src: '/images/history/session-03/field-03.webp', width: 1600, height: 746, alt: '나혜석거리 천막 아래 모여 이야기를 나누는 시민들', label: '함께한 시민들' },
      { src: '/images/history/session-03/field-04.webp', width: 1600, height: 1200, alt: '아이와 가족도 함께한 공정선거 시민행동 3회차 현장', label: '가족이 함께한 광장' },
      { src: '/images/history/session-03/field-05.webp', width: 1920, height: 895, alt: '손팻말을 든 시민과 가족이 함께한 공정선거 시민행동 3회차', label: '가족과 함께' },
      { src: '/images/history/session-03/field-06.webp', width: 1920, height: 895, alt: '태극기를 펼치고 거리에서 메시지를 전하는 3회차 참가자', label: '태극기 시민 발언' },
      { src: '/images/history/session-03/field-07.webp', width: 1920, height: 895, alt: '나혜석거리 천막 앞에서 손팻말을 들고 선 시민', label: '거리의 손팻말' },
      { src: '/images/history/session-03/field-08.webp', width: 1920, height: 895, alt: '공정선거 메시지를 들고 발언을 이어가는 시민행동 참가자', label: '이어진 발언' },
      { src: '/images/history/session-03/field-09.webp', width: 1920, height: 895, alt: '천막 아래 모여 시민의 목소리를 듣는 3회차 현장', label: '천막 아래 시민들' },
      { src: '/images/history/session-03/field-10.webp', width: 1920, height: 895, alt: '태극기와 시민행동 부스가 함께 보이는 나혜석거리 전경', label: '나혜석거리 전경' },
      { src: '/images/history/session-03/field-11.webp', width: 1920, height: 895, alt: '아이와 가족이 오가는 3회차 시민행동 천막 현장', label: '아이들이 찾은 광장' },
      { src: '/images/history/session-03/field-12.webp', width: 1920, height: 895, alt: '가족과 시민이 함께 머문 공정선거 시민행동 3회차', label: '함께 머문 시간' },
      { src: '/images/history/session-03/field-13.webp', width: 1920, height: 895, alt: '나혜석거리에서 태극기와 손팻말을 들고 참여한 시민들', label: '광장의 메시지' },
      { src: '/images/history/session-03/field-14.webp', width: 768, height: 1150, alt: '공정선거 시민행동 3회차 현장의 여러 장면을 모은 기록', label: '3회차 모아보기' },
    ],
  },
  {
    date: '2026. 07. 04',
    session: '4회차',
    time: '17:00 — 19:00',
    place: '인계동 나혜석거리',
    title: '여름 저녁으로 시간을 옮기다',
    body: '여름 날씨에 맞춰 시간을 오후 5시로 변경하고 공개 채팅으로 참여 안내를 이어갔습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DaK0YJbEmHt',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-04-main.jpeg', width: 360, height: 510, alt: '6월 3일 이후 시간이 멈췄습니다 공정선거 시민행동 4회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-04-sunset.jpeg', width: 360, height: 510, alt: '자유민주주의 시간이 멈췄습니다 공정선거 시민행동 4회차 포스터', label: '태극기 시안' },
    ],
    photos: [
      { src: '/images/history/session-04/field-01.webp', width: 1600, height: 746, alt: '공정선거 시민행동 4회차 현장에 준비된 물품 상자', label: '현장 준비' },
      { src: '/images/history/session-04/field-02.webp', width: 1600, height: 746, alt: '여름 집회를 위해 준비한 음료와 간식', label: '시민을 위한 음료' },
      { src: '/images/history/session-04/field-03.webp', width: 1600, height: 746, alt: '나혜석거리 천막 앞에 모인 4회차 참가자들', label: '4회차 광장' },
      { src: '/images/history/session-04/field-04.webp', width: 1600, height: 746, alt: '태극기와 현수막이 놓인 공정선거 시민행동 4회차 현장', label: '거리의 기록' },
      { src: '/images/history/session-04/field-05.webp', width: 1920, height: 895, alt: '더운 날씨에 시민들을 위해 준비한 음료와 간식', label: '여름 간식 준비' },
      { src: '/images/history/session-04/field-06.webp', width: 1920, height: 895, alt: '공정선거 시민행동 4회차 참가자들에게 나눌 포장 간식', label: '나눔 간식' },
      { src: '/images/history/session-04/field-07.webp', width: 1920, height: 895, alt: '시민에게 전할 문구를 담아 준비한 4회차 간식', label: '메시지를 담은 간식' },
      { src: '/images/history/session-04/field-08.webp', width: 768, height: 690, alt: '현장 준비부터 시민 참여까지 담은 공정선거 시민행동 4회차 사진 모음', label: '4회차 모아보기' },
    ],
  },
  {
    date: '2026. 07. 11',
    session: '5회차',
    time: '17:00 — 19:00',
    place: '나혜석거리 인근',
    title: '비가 와도 이어진 다섯 번째 행동',
    body: '우천 안내와 준비 인원 모집을 공개하고 지역 상점 이용을 함께 요청했습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/Dac_eoAEvX-',
    source: '전시언 Threads 공지',
    posters: [
      { src: '/images/posters/suwon-action-05-main.jpeg', width: 360, height: 540, alt: '무엇이든 말하고 싶습니다 공정선거 시민행동 5회차 포스터', label: '대표 포스터' },
      { src: '/images/posters/suwon-action-05-crowd.jpeg', width: 360, height: 540, alt: '공정선거 재선거 당일투표 수개표 시민행동 5회차 포스터', label: '현장 시안' },
    ],
    photos: [
      { src: '/images/history/session-05/field-01.webp', width: 1553, height: 1600, alt: '각자의 메시지와 태극기를 들고 선 공정선거 시민행동 5회차 참가자들', label: '각자의 목소리' },
      { src: '/images/history/session-05/field-02.webp', width: 768, height: 1150, alt: '시민과 가족이 함께한 공정선거 시민행동 5회차 현장 사진 모음', label: '5회차 모아보기' },
    ],
  },
  {
    date: '2026. 07. 18',
    session: '6회차',
    time: '17:00 — 19:00',
    place: '나혜석거리 인근',
    title: '무엇이든 말할 수 있는 광장',
    body: '정해진 답보다 시민 각자의 목소리를 존중하는 여섯 번째 수원 행동을 열었습니다.',
    link: 'https://www.threads.com/@fairly_evenly/post/DaxpHAskiKm',
    source: '전시언 Threads 포스터',
    posters: [
      { src: '/images/posters/suwon-action-06-main.jpeg', width: 360, height: 510, alt: '공정선거 재선거 당일투표 수개표 시민행동 6회차 포스터', label: '대표 포스터' },
    ],
    photos: [
      { src: '/images/history/session-06/field-01.webp', width: 739, height: 1600, alt: '공정선거 시민행동 6회차 현장에 준비된 간식', label: '현장 간식' },
      { src: '/images/history/session-06/field-02.webp', width: 1600, height: 1200, alt: '여름 광장을 위해 준비한 음료와 물', label: '여름 광장 준비' },
      { src: '/images/history/session-06/field-03.webp', width: 1600, height: 1200, alt: '태극 문양 옷을 맞춰 입은 가족 참가자들', label: '가족 참가자' },
      { src: '/images/history/session-06/field-04.webp', width: 1200, height: 1600, alt: '나혜석거리 분수 앞 시민행동 부스와 참가자들', label: '6회차 현장' },
      { src: '/images/history/session-06/field-05.webp', width: 1920, height: 1440, alt: '무더운 여름 현장을 위해 얼음과 음료를 채운 보냉 상자', label: '시원한 음료 준비' },
      { src: '/images/history/session-06/field-06.webp', width: 768, height: 460, alt: '간식과 음료, 가족 참가자와 천막 현장을 모은 6회차 기록', label: '6회차 모아보기' },
    ],
  },
  {
    date: '2026. 07. 25',
    session: '7회차',
    time: '17:00 — 19:00',
    place: '인계동 나혜석거리',
    title: '낮과 밤, 함께 만드는 일곱 번째 광장',
    body: '가족이 함께하는 낮의 활기와 청년이 연결되는 밤의 에너지를 담은 두 시안으로 일곱 번째 수원 행동을 알렸습니다.',
    link: 'https://www.threads.com/@fairly_evenly?hl=ko',
    source: '전시언 공식 Threads',
    posters: [
      { src: '/images/posters/suwon-action-07-day.jpeg', width: 1024, height: 1535, alt: '가족이 수박을 나누는 공정선거 시민행동 7회차 낮 포스터', label: '낮 시안' },
      { src: '/images/posters/suwon-action-07-night.jpeg', width: 1024, height: 1536, alt: '시민들이 응원봉을 든 공정선거 시민행동 7회차 밤 포스터', label: '밤 시안' },
    ],
    photos: [
      { src: '/images/history/session-07/field-01.webp', width: 1600, height: 1200, alt: '태극기와 손팻말을 든 공정선거 시민행동 7회차 참가자들', label: '7회차 광장' },
      { src: '/images/history/session-07/field-02.webp', width: 1600, height: 1200, alt: '나혜석거리 천막 아래에서 시민과 대화하는 참가자들', label: '시민과의 대화' },
      { src: '/images/history/session-07/field-03.webp', width: 1600, height: 1200, alt: '테이블에서 현장 참여 안내를 진행하는 모습', label: '참여 안내' },
      { src: '/images/history/session-07/field-04.webp', width: 768, height: 230, alt: '광장과 천막, 시민 참여 안내를 함께 담은 7회차 현장 사진 모음', label: '7회차 모아보기' },
    ],
  },
  {
    date: '2026. 08. 01',
    session: '8회차',
    time: '시간 확인 중',
    place: '인계동 나혜석거리',
    title: '태극기와 함께 이어진 여덟 번째 현장',
    body: '큰 태극기와 시민행동 천막이 나혜석거리에 다시 섰습니다. 직접 제공된 현장 사진으로 여덟 번째 기록을 먼저 남깁니다.',
    posters: [],
    photos: [
      { src: '/images/history/session-08/field-01.webp', width: 1650, height: 2200, alt: '큰 태극기와 시민행동 천막이 함께 보이는 나혜석거리 8회차 현장', label: '태극기가 선 광장' },
    ],
  },
];

export const olgongTwoCut = {
  eyebrow: 'A NEW WAY TO GATHER',
  title: '사진을 찍는 순간만큼은 웃을 수 있게',
  summary: '올공두컷은 현장 부스에서 시작해, 누구나 휴대폰으로 찍을 수 있는 공개 포토부스로 확장된 시민 콘텐츠입니다.',
  principle: '사진값은 돈이 아니라 서로를 달래는 말 한마디입니다. 언성이 높아지는 순간에도 심판처럼 서기보다 "괜찮아, 그 마음 이해해"라고 다독이는 평화로운 참여를 요청합니다.',
  relationNote: '공정선거시민행동 현장에서 함께 소개된 시민 참여형 콘텐츠로 기록합니다.',
  appUrl: 'https://photobooth-ecru-phi.vercel.app',
  sourceUrl: 'https://www.threads.com/@gibalza_/post/DZyjAFyj-Rw',
  stepsUrl: 'https://www.threads.com/@gibalza_/post/DZyjAazD7sX',
  points: [
    ['OPEN', '부스 이후에도 누구나 휴대폰에서 찍을 수 있게 공개했습니다.'],
    ['PLAY', '프레임을 고르고 5장을 찍은 뒤, 마음에 드는 2장을 내려받습니다.'],
    ['PEACE', '밝은 사진 한 장으로 현장의 긴장을 낮추는 참여 문화를 만듭니다.'],
  ],
};

const pressVisuals = {
  'https://n.news.naver.com/article/003/0014004541': {
    image: '/images/news/suwon-olympic-park-crowd.webp',
    imageAlt: '수원 올림픽공원 산책로를 따라 함께한 공정선거 시민행동 참가자들',
    imageCredit: '공정선거시민행동 제공',
    imageFocus: 'field-crowd',
  },
  'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 올림픽공원에서 열린 재선거 촉구 집회',
    imageCredit: '동일 현장 사진 · 연합뉴스 이영주',
    imageFocus: 'speaker',
  },
  'https://www.yna.co.kr/view/AKR20260613033400061': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '유모차를 끌고 온 가족과 지역 주민들',
    imageCredit: '연합뉴스',
    imageFocus: 'speaker-center',
  },
  'https://www.yna.co.kr/view/AKR20260613033400061?amp=1': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '유모차를 끌고 온 가족과 지역 주민들',
    imageCredit: '연합뉴스',
    imageFocus: 'speaker-center',
  },
  'https://n.news.naver.com/article/437/0000496019': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 집회 현장의 시민들',
    imageCredit: '연합뉴스TV',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/016/0002656079': {
    image: '/images/news/herald-suwon.jpg',
    imageAlt: '투표용지 부족 규탄 시위 경기까지',
    imageCredit: '헤럴드경제',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/422/0000874401': {
    image: '/images/news/yonhap-tv.jpg',
    imageAlt: '연합뉴스TV 보도 현장 화면',
    imageCredit: '연합뉴스TV',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/666/0000110606': {
    image: '/images/news/kyeonggi-vote.jpg',
    imageAlt: '경기지역 투표용지 부족 관련 현장 자료',
    imageCredit: '경기일보',
    imageFocus: 'speaker',
  },
  'https://www.kgnews.co.kr/news/article.html?no=899276': {
    image: '/images/news/kgnews-vote.jpg',
    imageAlt: '경기 36곳 투표용지 비상 현장',
    imageCredit: '경기신문',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/001/0016129186': {
    image: '/images/news/yna-vote.jpg',
    imageAlt: '투표지 추가 송부와 선거인 명부 누락 관련 자료',
    imageCredit: '연합뉴스',
    imageFocus: 'speaker',
  },
  'https://www.kyeongin.com/article/1765268': {
    image: '/images/news/kyeongin-vote.jpg',
    imageAlt: '경기도 투표소 현장',
    imageCredit: '경인일보',
    imageFocus: 'speaker',
  },
  'https://www.joongang.co.kr/article/25436607': {
    image: '/images/news/joongang-action.jpg',
    imageAlt: '올공두컷 부스와 수원 집회 현장',
    imageCredit: '중앙일보',
    imageFocus: 'speaker',
  },
  'https://n.news.naver.com/article/025/0003532986': {
    image: '/images/news/joongang-interview.jpg',
    imageAlt: '전시언 인터뷰 관련 보도 화면',
    imageCredit: '중앙일보',
    imageFocus: 'speaker',
  },
  'https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02145126645481720': {
    image: '/images/news/edaily-olgong.jpg',
    imageAlt: '잠실에서 운영된 올공네컷 시민 체험 공간',
    imageCredit: '이데일리',
    imageFocus: 'speaker',
  },
  'https://www.wikitree.co.kr/articles/1141627': {
    image: '/images/news/wikitree-olgong.jpg',
    imageAlt: '서울 올림픽공원 핸드볼경기장 앞에 모인 시민들',
    imageCredit: '위키트리',
  },
  'https://www.fnnews.com/news/202606101502443216': {
    image: '/images/news/fnnews-dashboard.png',
    imageAlt: '시민이 만든 디지털 상황판',
    imageCredit: '파이낸셜뉴스',
    imageFocus: 'speaker',
  },
  'https://naver.me/FjmwJ2Vn': {
    image: '/images/news/yna-families-main.png',
    imageAlt: '유모차부터 3대가 함께한 수원 집회 현장',
    imageCredit: '네이버링크 변환',
    imageFocus: 'speaker-center',
  },
  'https://naver.me/5B0t3BHW': {
    image: '/images/news/yna-suwon.jpg',
    imageAlt: '수원 재선거 촉구 집회 현장',
    imageCredit: '네이버링크 변환',
    imageFocus: 'speaker',
  },
};

const withPressVisual = (item) => ({ ...item, ...pressVisuals[item.href] });

export const organization = [
  ['01', '감사', '최문영'],
  ['02', '재무', '이철우'],
  ['03', '사무국장', '김민섭'],
  ['04', '특별위원장', '한동원'],
  ['05', '조직위원장', '박보환'],
  ['06', '청년위원장', '박장훈'],
  ['07', '기획위원장', '장동재'],
];

export const organizationPlans = [
  ['01', '고유번호증 발급 추진'],
  ['02', '단체 명의 통장 개설'],
  ['03', '회원 및 후원회원 모집'],
];

export const reports = [
  {
    id: 'yna-suwon-20260613',
    category: '수원 현장',
    relation: '1회차 · 수원 현장',
    usage: 'direct',
    media: '연합뉴스',
    date: '2026. 06. 13',
    title: '‘유모차부터 3대 가족까지’…수원서도 ‘재선거 촉구’ 집회',
    summary: '수원 올림픽공원에 모인 가족 단위 참가자와 시민들의 참여를 기록한 현장 보도입니다.',
    href: 'https://www.yna.co.kr/view/AKR20260613033400061',
  },
  {
    id: 'newsis-suwon-20260613',
    category: '수원 현장',
    relation: '1회차 · 수원 올림픽공원',
    usage: 'direct',
    media: '뉴시스',
    date: '2026. 06. 13',
    title: '‘부정선거 재선거’ 유모차 끌고, 돗자리 깔고…수원도 시민들 모여[현장]',
    summary: '올림픽공원 현장의 가족 단위 참여와 현장 동학을 담았습니다.',
    href: 'https://n.news.naver.com/article/003/0014004541',
  },
  {
    id: 'tvchosun-suwon-20260613',
    category: '수원 현장',
    relation: '1회차 · 수원 현장',
    usage: 'direct',
    media: 'TV조선',
    date: '2026. 06. 13',
    title: '수원서도 재선거 촉구 집회…시민 40여명 규탄',
    summary: '현장 집회와 시민 참여 분위기를 다뤘습니다.',
    href: 'https://news.tvchosun.com/site/data/html_dir/2026/06/13/2026061390047.html',
  },
  {
    id: 'jtbc-suwon-20260613',
    category: '수원 현장',
    relation: '수원 시민행동 확산',
    usage: 'direct',
    media: 'JTBC',
    date: '2026. 06. 13',
    title: '수원까지 번진 재선거 촉구 집회',
    summary: '수원 일대의 연대 확산을 중심으로 한 보도입니다.',
    href: 'https://n.news.naver.com/article/437/0000496019',
  },
  {
    id: 'herald-gyeonggi-20260613',
    category: '관련 보도',
    relation: '경기권 시민행동',
    usage: 'related',
    media: '헤럴드경제',
    date: '2026. 06. 13',
    title: '투표용지 부족 규탄 시위 경기까지 확산',
    summary: '수원권 집회와 경기 지역 확산 보도를 함께 정리한 기사입니다.',
    href: 'https://n.news.naver.com/article/016/0002656079',
  },
  {
    id: 'yonhap-tv-election-20260613',
    category: '관련 보도',
    relation: '투표지 부족 관련 발표',
    usage: 'related',
    media: '연합뉴스',
    date: '2026. 06. 13',
    title: '[뉴스1번지] 투표지 부족 관련 발표와 규탄',
    summary: '투표지 부족 보도 속 수원 집회 언급을 함께 다루었습니다.',
    href: 'https://n.news.naver.com/article/422/0000874401',
  },
  {
    id: 'joongang-olgong-20260614',
    category: '단체·인물',
    relation: '현장에서 함께 소개된 시민 콘텐츠',
    usage: 'citizen',
    project: 'olgong',
    media: '중앙일보',
    date: '2026. 06. 14',
    title: '朴·尹 탄핵찬성했던 청년 ‘올공두컷’ 부스 차렸다…열흘째 체육단체는 마비',
    summary: '수원 1회차 집회와 올공두컷 현장 조각을 함께 담았습니다.',
    href: 'https://www.joongang.co.kr/article/25436607',
  },
  {
    id: 'joongang-interview-20260625',
    category: '인터뷰',
    relation: '전시언 · 투표 연장 문제',
    usage: 'interview',
    media: '중앙일보',
    date: '2026. 06. 25',
    title: '[단독] 0분부터 240분까지…투표 멈춘 곳들 시간 기준',
    summary: '확대 적용 시점의 시간 기준을 짚은 인터뷰형 기사입니다.',
    href: 'https://n.news.naver.com/article/025/0003532986',
  },
  {
    id: 'edaily-olgong-20260614',
    category: '현장 콘텐츠',
    relation: '현장에서 함께 소개된 시민 콘텐츠',
    usage: 'citizen',
    project: 'olgong',
    media: '이데일리',
    date: '2026. 06. 14',
    title: '‘잠실 개표소 시위’서 무료 과외·올공네컷 등 이색 체험존 등장…경찰은 장기전 대비',
    summary: 'AI로 프레임을 제작하고 현장 프린터로 사진을 제공한 올공두컷 체험존을 소개했습니다.',
    href: 'https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02145126645481720',
  },
  {
    id: 'wikitree-olgong-20260617',
    category: '현장 콘텐츠',
    relation: '현장에서 함께 소개된 시민 콘텐츠',
    usage: 'citizen',
    project: 'olgong',
    media: '위키트리',
    date: '2026. 06. 17',
    title: '아기띠 둘러메고 커플끼리 손잡고…시민 발길 이어진 올림픽공원 속 목소리 [르포]',
    summary: '가족·청년 참가자와 자원봉사 현장을 취재하며 즉석사진을 인화해 주는 올공두컷을 함께 소개했습니다.',
    href: 'https://www.wikitree.co.kr/articles/1141627',
  },
  {
    id: 'fnnews-dashboard-20260610',
    category: '시민 기술',
    relation: '시민 제작 현장 정보',
    usage: 'citizen',
    media: '파이낸셜뉴스',
    date: '2026. 06. 10',
    title: '시민이 직접 만든 디지털 상황판',
    summary: '집회 정보와 현장 상황을 연결한 시민 기술 보도입니다.',
    href: 'https://www.fnnews.com/news/202606101502443216',
  },
  {
    id: 'naver-suwon-network-20260613',
    category: '수원 현장',
    relation: '수원 집회 네트워킹',
    usage: 'direct',
    media: '연합뉴스',
    date: '2026. 06. 13',
    title: '수원 집회 네트워킹 참여 안내(요약)',
    summary: '네이버 링크 기반으로 수집한 집회 보도 원문을 함께 제공합니다.',
    href: 'https://naver.me/FjmwJ2Vn',
  },
  {
    id: 'naver-suwon-growth-20260613',
    category: '수원 현장',
    relation: '수원 시민 참여 확산',
    usage: 'direct',
    media: 'JTBC',
    date: '2026. 06. 13',
    title: '수원 재선거 촉구 집회 참여 증가 현장 보도(요약)',
    summary: '네이버 링크 기반으로 시민 확산 보도 원문을 함께 제공합니다.',
    href: 'https://naver.me/5B0t3BHW',
  },
].map(withPressVisual);

export const historyEvidenceIds = [
  'yna-suwon-20260613',
  'tvchosun-suwon-20260613',
  'newsis-suwon-20260613',
  'joongang-olgong-20260614',
  'joongang-interview-20260625',
];

export const reportsById = Object.fromEntries(reports.map((report) => [report.id, report]));

export const getReportsByIds = (ids) => ids.map((id) => reportsById[id]).filter(Boolean);
